Added error handling for git clone

diff --git a/scripts/venv/run_dora b/scripts/venv/run_dora
--- a/scripts/venv/run_dora
+++ b/scripts/venv/run_dora
@@ -17,6 +17,11 @@ python3.12 -m venv $smlp_venv_dir
 cd $smlp_venv_dir
 source bin/activate
 git clone https://github.com/SMLP-Systems/smlp
+exit_code=$?
+if [ $exit_code -ne 0 ]; then
+    echo "ERROR: git clone failed"
+    exit 1
+fi
 GIT_BRANCH=$(git branch --show-current)
 cd smlp
 if [ $(git branch -r --list origin/$GIT_BRANCH) ]; then
